# Generated by Django 4.2.3 on 2023-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('associated_to', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
                ('alternate_text', models.CharField(max_length=250)),
                ('header', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'moment',
                'verbose_name_plural': 'moments',
            },
        ),
    ]
