# Generated by Django 4.2.3 on 2023-09-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedMoment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('associated_to', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
                ('alternate_text', models.CharField(max_length=250)),
                ('header', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.moment')),
            ],
            options={
                'verbose_name': 'embedded moment',
                'verbose_name_plural': 'embedded moments',
            },
        ),
    ]
