# Generated by Django 4.2.3 on 2023-08-04 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('associated_to', models.CharField(blank=True, max_length=250, null=True)),
                ('DOP', models.DateField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
                ('alternate_text_for_image', models.CharField(blank=True, max_length=250, null=True)),
                ('article', models.TextField()),
                ('youtube_video_url', models.CharField(blank=True, max_length=250, null=True)),
                ('published_at', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Thought',
                'verbose_name_plural': 'Thoughts',
            },
        ),
    ]
