# Generated by Django 4.2.3 on 2023-08-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoughts',
            new_name='ThoughtsV1',
        ),
    ]
