# Generated by Django 4.2.3 on 2023-09-02 14:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_rename_thoughts_thoughtsv1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtsv1',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to=''),
        ),
    ]
